Repository palantir/conjure-go, pull requests merged in 2020-11, with the labels that each got.

#162 [break] Render enums as structs instead of string aliases
  changelog/@unreleased/pr-162.v2.yml
  conjure-api/conjure/spec/enums.conjure.go
  conjure-go-verifier/conjure/verification/types/enums.conjure.go
  conjure/aliaswriter_test.go
  conjure/conjure_test.go
  conjure/enum.go
  conjure/enum_test.go
  conjure/errorwriter.go
  conjure/serverwriter.go
  conjure/servicewriter.go
  conjure/visitors/conjuretype_test.go
  conjure/visitors/conjuretype_visit_external_test.go
  conjure/visitors/conjuretype_visit_primitive.go
  conjure/visitors/visit_http_param.go
  conjure/visitors/visit_http_param_test.go
  go.mod
  go.sum
  integration_test/testgenerated/objects/api/enums.conjure.go
  integration_test/testgenerated/objects/objects.yml
  integration_test/testgenerated/objects/objects_test.go
  vendor/github.com/danverbraganza/varcaser/LICENSE.txt
  vendor/github.com/danverbraganza/varcaser/varcaser/caseconvention.go
  vendor/github.com/danverbraganza/varcaser/varcaser/caser.go
  vendor/github.com/danverbraganza/varcaser/varcaser/detector.go
  vendor/github.com/danverbraganza/varcaser/varcaser/varcaser.go
  vendor/modules.txt
Labels: merge when ready

#166 Break: Bump go module to v6
  changelog/@unreleased/pr-166.v2.yml
  cmd/root.go
  conjure-go-verifier/conjure/verification/server/services.conjure.go
  conjure-go-verifier/generate/generate.go
  conjure-go-verifier/verifier_test.go
  conjure/aliaswriter.go
  conjure/aliaswriter_test.go
  conjure/config.go
  conjure/conjure.go
  conjure/conjure_test.go
  conjure/encoding_methods.go
  conjure/enum.go
  conjure/enum_test.go
  conjure/errorwriter.go
  conjure/objectwriter.go
  conjure/serverwriter.go
  conjure/servicewriter.go
  conjure/transforms/transforms.go
  conjure/transforms/transforms_test.go
  conjure/types/customtype_test.go
  conjure/types/pkg_info_test.go
  conjure/types/types.go
  conjure/unionwriter.go
  conjure/visitors/conjuretype_provider.go
  conjure/visitors/conjuretype_provider_visitor.go
  conjure/visitors/conjuretype_test.go
  conjure/visitors/conjuretype_visit_external.go
  conjure/visitors/conjuretype_visit_external_test.go
  conjure/visitors/conjuretype_visit_list.go
  conjure/visitors/conjuretype_visit_map.go
  conjure/visitors/conjuretype_visit_optional.go
  conjure/visitors/conjuretype_visit_primitive.go
  conjure/visitors/conjuretype_visit_reference.go
  conjure/visitors/conjuretype_visit_set.go
  conjure/visitors/filter_auth_type.go
  conjure/visitors/filter_param_type.go
  conjure/visitors/visit_conjure_definition.go
  conjure/visitors/visit_custom_conjure_types.go
  conjure/visitors/visit_http_param.go
  conjure/visitors/visit_http_param_test.go
  conjure/visitors/visit_packages.go
  conjure/visitors/visit_param_id.go
  conjure/visitors/visit_type_definitions.go
  go.mod
  go.sum
  integration_test/integration_test.go
  integration_test/testgenerated/auth/auth_test.go
  integration_test/testgenerated/client/clientparam_test.go
  integration_test/testgenerated/errors/errors_test.go
  integration_test/testgenerated/generate.go
  integration_test/testgenerated/objects/objects_test.go
  integration_test/testgenerated/post/postparam_test.go
  integration_test/testgenerated/queryparam/queryparam_test.go
  integration_test/testgenerated/server/clientparam_test.go
  integration_test/testgenerated/server/server_test.go
  main.go
Labels: merge when ready

#168 Release 6.0.1
  changelog/6.0.1/pr-167.v2.yml
Labels: no changelog

#169 Fix: Don't fail deserialization on invalid enum values
  changelog/@unreleased/pr-169.v2.yml
  conjure-api/conjure/spec/enums.conjure.go
  conjure-go-verifier/conjure/verification/types/enums.conjure.go
  conjure-go-verifier/ignored-test-cases.yml
  conjure/conjure.go
  conjure/conjure_test.go
  conjure/enum.go
  conjure/enum_test.go
  integration_test/testgenerated/objects/api/enums.conjure.go
  integration_test/testgenerated/objects/objects_test.go
Labels: merge when ready

#170 Improvement: Use latest CGR wrapped error helpers
  changelog/@unreleased/pr-170.v2.yml
  conjure/conjure_test.go
  conjure/errorwriter.go
  conjure/serverwriter.go
  integration_test/testgenerated/auth/api/servers.conjure.go
  integration_test/testgenerated/errors/api/errors.conjure.go
  integration_test/testgenerated/post/api/servers.conjure.go
  integration_test/testgenerated/queryparam/queryparam_test.go
  integration_test/testgenerated/server/api/servers.conjure.go
Labels: autorelease, merge when ready
