Repository palantir/conjure-go, pull requests merged in 2020-10, with the labels that each got.

#145 Add VisitorWithContext interface generation.
  changelog/@unreleased/pr-145.v2.yml
  conjure-api/conjure/spec/unions.conjure.go
  conjure-go-verifier/conjure/verification/types/unions.conjure.go
  conjure/conjure_test.go
  conjure/types/types.go
  conjure/unionwriter.go
  integration_test/testgenerated/objects/api/unions.conjure.go
Labels: merge when ready

#146 Update verifier_test to confirm ignored cases before erroring
  conjure-go-verifier/ignored-test-cases.yml
  conjure-go-verifier/verifier_test.go
Labels: no changelog

#147 Upgrade conjure-verification version
  .circleci/config.yml
  conjure-go-verifier/conjure/verification/server/services.conjure.go
  conjure-go-verifier/conjure/verification/server/structs.conjure.go
  conjure-go-verifier/conjure/verification/types/aliases.conjure.go
  conjure-go-verifier/conjure/verification/types/enums.conjure.go
  conjure-go-verifier/conjure/verification/types/structs.conjure.go
  conjure-go-verifier/generate/generate.go
  conjure-go-verifier/ignored-test-cases.yml
  conjure-go-verifier/verification-server-api.conjure.json
  conjure-go-verifier/verification-server-test-cases.json
  conjure-go-verifier/version_test.go
Labels: no changelog

#150 Bump go to 1.15.2 in build
  .circleci/config.yml
Labels: merge when ready, no changelog

#151 Improvement: Generate IsErrorType helpers for conjure errors
  changelog/@unreleased/pr-151.v2.yml
  conjure/conjure_test.go
  conjure/errorwriter.go
  integration_test/testgenerated/errors/api/errors.conjure.go
  integration_test/testgenerated/errors/errors_test.go
Labels: merge when ready

#160 Add IsUnknown() and Values() funcs for enums
  changelog/@unreleased/pr-160.v2.yml
  conjure-api/conjure/spec/enums.conjure.go
  conjure-go-verifier/conjure/verification/types/enums.conjure.go
  conjure/conjure_test.go
  conjure/enum.go
  conjure/enum_test.go
  integration_test/testgenerated/objects/api/enums.conjure.go
  integration_test/testgenerated/objects/objects_test.go
Labels: autorelease, merge when ready
