Repository palantir/conjure-go, pull requests merged in 2021-07, with the labels that each got.

#211 Improvement: Add errorName as safe param to generated errors
  changelog/@unreleased/pr-211.v2.yml
  conjure/conjure_test.go
  conjure/errorwriter.go
  integration_test/testgenerated/errors/api/errors.conjure.go
Labels: autorelease, merge when ready

#212 fix changelog
  changelog/@unreleased/pr-211.v2.yml
Labels: autorelease, merge when ready

#213 Set test parallelism to 1 to address flake
  .circleci/config.yml
Labels: no changelog

#215 Improvement: Generate default functions for use with AcceptFuncs union visitor method
  changelog/@unreleased/pr-215.v2.yml
  conjure/conjure_test.go
  conjure/unionwriter.go
  integration_test/testgenerated/objects/api/unions.conjure.go
  integration_test/testgenerated/objects/objects_test.go
Labels: merge when ready
