Repository palantir/conjure-go, pull requests merged in 2022-05, with the labels that each got.

#300 Propose generic visitor interfaces for union types
  changelog/@unreleased/pr-300.v2.yml
  conjure-api/conjure/spec/unions_generics.conjure.go
  conjure-go-verifier/conjure/verification/types/unions_generics.conjure.go
  conjure/conjure.go
  conjure/snip/imports.go
  conjure/unionwriter.go
  conjure/unionwriter_test.go
  integration_test/testgenerated/imports/pkg3/api/unions_generics.conjure.go
  integration_test/testgenerated/objects/api/unions_generics.conjure.go
Labels: autorelease

#305 Improvement: Add verbose mode to generated CLIs
  changelog/@unreleased/pr-305.v2.yml
  conjure/cliwriter.go
  conjure/snip/imports.go
  integration_test/testgenerated/auth/api/cli.conjure.go
  integration_test/testgenerated/binary/api/cli.conjure.go
  integration_test/testgenerated/cli/api/cli.conjure.go
  integration_test/testgenerated/client/api/cli.conjure.go
  integration_test/testgenerated/post/api/cli.conjure.go
  integration_test/testgenerated/queryparam/api/cli.conjure.go
  integration_test/testgenerated/server/api/cli.conjure.go
Labels: autorelease, merge when ready

#306 Improvement: Generated CLIs support input via file, base64, and STDIN
  changelog/@unreleased/pr-306.v2.yml
  conjure/cliwriter.go
  conjure/snip/imports.go
  integration_test/testgenerated/binary/api/cli.conjure.go
  integration_test/testgenerated/cli/api/cli.conjure.go
  integration_test/testgenerated/cli/api/enums.conjure.go
  integration_test/testgenerated/cli/api/servers.conjure.go
  integration_test/testgenerated/cli/api/services.conjure.go
  integration_test/testgenerated/cli/api/unions.conjure.go
  integration_test/testgenerated/cli/api/unions_generics.conjure.go
  integration_test/testgenerated/cli/cli-service.yml
  integration_test/testgenerated/cli/cli_test.go
  integration_test/testgenerated/queryparam/api/cli.conjure.go
  integration_test/testgenerated/server/api/cli.conjure.go
  internal/generated/mocks/github.com/palantir/conjure-go/v6/integration_test/testgenerated/cli/api/servers.conjure_mocks.go
  internal/generated/mocks/github.com/palantir/conjure-go/v6/integration_test/testgenerated/cli/api/services.conjure_mocks.go
  internal/generated/mocks/github.com/palantir/conjure-go/v6/integration_test/testgenerated/cli/api/unions.conjure_mocks.go
Labels: autorelease, merge when ready

#312 Fix: Fix typo in default generated CLI conf path
  changelog/@unreleased/pr-312.v2.yml
  conjure/cliwriter.go
  integration_test/testgenerated/auth/api/cli.conjure.go
  integration_test/testgenerated/binary/api/cli.conjure.go
  integration_test/testgenerated/cli/api/cli.conjure.go
  integration_test/testgenerated/client/api/cli.conjure.go
  integration_test/testgenerated/post/api/cli.conjure.go
  integration_test/testgenerated/queryparam/api/cli.conjure.go
  integration_test/testgenerated/server/api/cli.conjure.go
Labels: merge when ready
