Repository palantir/conjure-go, pull requests merged in 2024-11, with the labels that each got.

#629 improvement: Build with go 1.22.8 and godel 2.121.0
  .circleci/config.yml
  .palantir/go-version
  changelog/@unreleased/pr-629.v2.yml
  go.mod
  go.sum
  godel/config/godel.properties
  godelw
  vendor/github.com/palantir/witchcraft-go-server/v2/witchcraft/internal/wdebug/handlers.go
  vendor/github.com/palantir/witchcraft-go-server/v2/witchcraft/server_state.go
  vendor/github.com/palantir/witchcraft-go-server/v2/witchcraft/witchcraft.go
  vendor/github.com/palantir/witchcraft-go-server/v2/wrouter/README.md
  vendor/github.com/palantir/witchcraft-go-server/v2/wrouter/pathtemplate.go
  vendor/github.com/palantir/witchcraft-go-server/v2/wrouter/router_root.go
  vendor/modules.txt
Labels: merge when ready

#626 Fix: Update local type alias naming scheme to prevent conflicts with object field types
  changelog/@unreleased/pr-626.v2.yml
  conjure-api/conjure/spec/structs.conjure.go
  conjure-go-verifier/conjure/verification/server/structs.conjure.go
  conjure-go-verifier/conjure/verification/types/structs.conjure.go
  conjure/objectwriter.go
  conjure/objectwriter_test.go
  cycles/testdata/cycle-within-pkg/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/no-cycles/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/no-cycles/conjure/com/palantir/foo/structs.conjure.go
  cycles/testdata/pkg-cycle-disconnected/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/pkg-cycle-disconnected/conjure/com/palantir/foo/structs.conjure.go
  cycles/testdata/pkg-cycle/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/pkg-cycle/conjure/com/palantir/foo1/structs.conjure.go
  cycles/testdata/type-cycle/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/type-cycle/conjure/com/palantir/foo/structs.conjure.go
  integration_test/testgenerated/errors/api/errors.conjure.go
  integration_test/testgenerated/objects/api/structs.conjure.go
Labels: bug, autorelease, merge when ready

#620 improvement: Upgrade CGR and use httpclient.RequestBody for binary uploads
  changelog/@unreleased/pr-620.v2.yml
  conjure-go-verifier/conjure/verification/server/services.conjure.go
  conjure/cliwriter.go
  conjure/servicewriter.go
  conjure/snip/imports.go
  go.mod
  go.sum
  godel/config/mockgen-plugin.yml
  integration_test/testgenerated/auth/api/cli.conjure.go
  integration_test/testgenerated/binary/api/cli.conjure.go
  integration_test/testgenerated/binary/api/services.conjure.go
  integration_test/testgenerated/binary/binary_test.go
  integration_test/testgenerated/cli/api/cli.conjure.go
  integration_test/testgenerated/cli/api/services.conjure.go
  integration_test/testgenerated/cli/cli_test.go
  integration_test/testgenerated/client/api/cli.conjure.go
  integration_test/testgenerated/post/api/cli.conjure.go
  integration_test/testgenerated/queryparam/api/cli.conjure.go
  integration_test/testgenerated/server/api/cli.conjure.go
  integration_test/testgenerated/server/api/services.conjure.go
  internal/generated/mocks/github.com/palantir/conjure-go/v6/integration_test/testgenerated/cli/api/cli.conjure_mocks.go
  internal/generated/mocks/github.com/palantir/conjure-go/v6/integration_test/testgenerated/cli/api/servers.conjure_mocks.go
  internal/generated/mocks/github.com/palantir/conjure-go/v6/integration_test/testgenerated/cli/api/services.conjure_mocks.go
  internal/generated/mocks/github.com/palantir/conjure-go/v6/integration_test/testgenerated/cli/api/unions.conjure_mocks.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient/body_handler.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient/body_types.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient/client.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient/request_params.go
  vendor/modules.txt
Labels: autorelease, merge when ready

#636 Internal error registry per package
  changelog/@unreleased/pr-636.v2.yml
  conjure/conjure.go
  conjure/errorwriter.go
  conjure/servicewriter.go
  conjure/snip/imports.go
  conjure/types/conjure_definition.go
  conjure/types/output_paths.go
  cycles/testdata/cycle-within-pkg/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/cycle-within-pkg/conjure/com/palantir/services/services.conjure.go
  cycles/testdata/cycle-within-pkg/conjure/internal/conjureerrors/error_registry.conjure.go
  cycles/testdata/no-cycles/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/no-cycles/conjure/com/palantir/services/services.conjure.go
  cycles/testdata/no-cycles/conjure/internal/conjureerrors/error_registry.conjure.go
  cycles/testdata/pkg-cycle-disconnected/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/pkg-cycle-disconnected/conjure/com/palantir/services/services.conjure.go
  cycles/testdata/pkg-cycle-disconnected/conjure/internal/conjureerrors/error_registry.conjure.go
  cycles/testdata/pkg-cycle/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/pkg-cycle/conjure/com/palantir/services/services.conjure.go
  cycles/testdata/pkg-cycle/conjure/internal/conjureerrors/error_registry.conjure.go
  cycles/testdata/type-cycle/conjure/com/palantir/errors/errors.conjure.go
  cycles/testdata/type-cycle/conjure/com/palantir/services/services.conjure.go
  cycles/testdata/type-cycle/conjure/internal/conjureerrors/error_registry.conjure.go
  go.mod
  go.sum
  integration_test/testgenerated/errors/api/errors.conjure.go
  integration_test/testgenerated/errors/errors_test.go
  integration_test/testgenerated/errors/internal/conjureerrors/error_registry.conjure.go
  vendor/github.com/dave/jennifer/jen/file.go
  vendor/github.com/dave/jennifer/jen/generated.go
  vendor/github.com/dave/jennifer/jen/generics.go
  vendor/github.com/dave/jennifer/jen/group.go
  vendor/github.com/dave/jennifer/jen/hints.go
  vendor/github.com/dave/jennifer/jen/jen.go
  vendor/github.com/dave/jennifer/jen/reserved.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient/request_params.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient/response_error_decoder_middleware.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors/conjure_error_decoder.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors/error_type_registry.go
  vendor/github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors/unmarshal.go
  vendor/modules.txt
Labels: autorelease, merge when ready
